- block:
  # - name: parted > override previous "{{ disk.device + _nvme_p + _part_sys_num }}" fs to avoid luks errors
  #   filesystem:
  #     fstype: vfat
  #     dev:    "{{ disk.device + _nvme_p + _part_sys_num }}"
  #     force:  yes

  ## A TESTER
  - name: luks | modprobe > load xts kernel module
    modprobe:
      name: xts

  - name: luks | luks_device > create then open new luks container
    luks_device:
      device:     "{{ item.device }}"
      name:       "{{ item.name   | default(default_luks_name) }}"
      passphrase: "{{ item.password }}"
      cipher:     "{{ item.cipher | default('aes-xts-plain64') }}"
      type:       "{{ item.type   | default('luks2')  }}"
      hash:       "{{ item.hash   | default('sha512') }}"
      label:      "{{ item.label  | default('luks') }}"
      pbkdf:
        iteration_time: 5
      # keyfile:    "{{ item.keyfile | default(omit) }}"
      state:      "{{ item.state  | default('opened') }}"
    with_items:
      - "{{ luks }}"

  when: luks_enable
  tags: luks
