- block:
  - name: luks | modprobe > load xts kernel module
    modprobe:
      name: xts

  - name: luks | luks_device > create then open new luks container
    luks_device:
      device:     "{{ item.device }}"
      name:       "{{ item.name   | default(default_luks_name) }}"
      passphrase: "{{ item.password }}"
      cipher:     "{{ item.cipher | default('aes-xts-plain64') }}"
      type:       "{{ item.type   | default('luks1')  }}"     ## change for luks2 when grub2 will fully implement it
      hash:       "{{ item.hash   | default('sha512') }}"
      label:      "{{ (item.label | default('luks')) if item.type == 'luks2' else omit }}"    # only available with luks2
      pbkdf:
        iteration_time: 5
      # keyfile:    "{{ item.keyfile | default(omit) }}"
      state:      "{{ item.state  | default('opened') }}"
    with_items:
      - "{{ luks }}"

  when: luks_enable
  tags: luks
