- block:
  - name: shell > enable swap partition
    shell: swapon {{ item.dev }}
    when: item.fstype == "swap"
    with_items: "{{ fs }}"

  # must mount ext4 on lvm or on primary partition, and boot partition
  - name: mount > partition.s, volume.s and subvolume.s
    mount:
      src:    "{{ item.dev }}"
      path:   "{{ chroot + item.path }}"
      fstype: "{{ item.fstype }}"
      opts:   "{{ item.mnt_opts  | default(omit)      }}"
      state:  "{{ item.state     | default('mounted') }}"
    when: item.fstype not in ["swap", "btrfs"]
    with_items:
      - "{{ fs }}"

  tags: mountt
