remove previous files
  ## TOUJOURS UTILE ?
  # - name: "[btrfs] [shell] list content of {{ chroot }}/home"
  #   shell: ls -la {{ chroot }}/home
  #   register: ls

  # - name: "[btrfs] [file] delete files on {{ chroot }}/home"
  #   file:
  #     path: "{{ chroot }}/home/{{ item }} "
  #     state: absent
  #   with_items: "{{ ls.stdout_lines }}"

  # - name: "[btrfs] [shell] list content of {{ chroot }}/boot"
  #   shell: ls -la {{ chroot }}/boot
  #   register: _ls

  # - name: "[btrfs] [file] delete files on {{ chroot }}/boot"
  #   file:
  #     path:  "{{ chroot }}/boot/{{ item }} "
  #     state: absent
  #   with_items: "{{ _ls.stdout_lines }}"

